### ISSUE TITLE
Import material error

### ISSUE THREAD

**Issue by TEXHAPb777** [Zode/blenderutils#2]
Python: Traceback (most recent call last):
  File "C:\Users\sanka\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderutils-master\material_operators.py", line 15, in execute
    if FixImportMaterials():
  File "C:\Users\sanka\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderutils-master\goldsrc\importmat.py", line 36, in FixImportMaterials
    bsdf.label = "Principled BSDF"
AttributeError: 'NoneType' object has no attribute 'label'

**Comment by Mikk155** [comment]
I am unsure how the whole SDK works so this is probably not a fix but will prevent the script from crashing.

- In between [#L36](https://github.com/Zode/blenderutils/blob/master/goldsrc/importmat.py#L36) and [#L37](https://github.com/Zode/blenderutils/blob/master/goldsrc/importmat.py#L37) add:
```python
if bsdf:
    continue;
```
Should look like:
```python
		bsdf = mat.node_tree.nodes.get("Principled BSDF")

		if bsdf:
			continue;

		bsdf.label = "Principled BSDF"
```
